# Generated by Django 4.0.3 on 2022-04-02 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_alter_news_options_alter_news_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, default='No category yet...', null=True, on_delete=django.db.models.deletion.PROTECT, to='news.category', verbose_name='Category'),
        ),
    ]
